version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "type: dependencies"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "type: dependencies"
    target-branch: "dev"
    schedule:
      interval: "daily"
    reviewers:
      - "VKumar786"
    open-pull-requests-limit: 10
    registries: "*"
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_DEP_TOKEN}}
  github-npmjs:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GIT_TOKEN}}
